name: Test CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Add GitHub Packages source
        run: dotnet nuget add source "https://nuget.pkg.github.com/bubus1kk/index.json" --name github --username bubus1kk --password ${{ secrets.PACKAGES_PAT }} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore FigureCalculatorLibrary.Test/FigureCalculatorLibraryTest/FigureCalculatorLibraryTest.csproj

      - name: Run tests
        run: dotnet test FigureCalculatorLibrary.Test/FigureCalculatorLibraryTest/FigureCalculatorLibraryTest.csproj --configuration Release --no-restore